apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  namespace: metallb-system
  name: <pool-name>
spec:
  addresses:
  - <NETID>.<START>-<NETID>.<END>
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: <pool-name>
  namespace: metallb-system